### PR TITLE
1.1.0

### PR DESCRIPTION
**Pull request by kennyt**
The API will stay exactly the same. Rework is much simpler and will allow for more precise selector elimination + leaving the order of the CSS files the same (currently, it orders the CSS files into selectors/at-rules)

The following issues should be fixed once this is merged in: #91 #85 #53

Going to be adding stronger tests before I merge this in for v1.1.0-beta

### CODE REVIEW

**Comment by IngwiePhoenix** [comment]
Anything I'd need to knwo in regards to the WebPack plugin? Does the PurifyCSS API change in any way? And which issues are addressed by the change to Rework?

Just curios for the most part, and wanting ot make sure the webpack plugin stays in sync.

**Comment by kennyt** [comment]
Added a description for the PR

**Comment by IngwiePhoenix** [comment]
Woah! #91 being fixed is amazing. Looking forward to this.

Keep up the great work man =)

**Comment by IngwiePhoenix** [comment]
As this is merged now, does the `-beta` still apply?

**Comment by kennyt** [comment]
Yes, this is in master, but it's still in beta

**Comment by kennyt** [comment]
@IngwiePhoenix just tested this on a really big app and it looks good. 1.1.1 is out!

**Comment by IngwiePhoenix** [comment]
Going to test 1.1.1 on the WebPack plugin and update that accordingly!

**Pull request merged**
