### PR TITLE
Added attribute selectors to fix #32

### LINKED ISSUE #32: Attribute Selectors
Purify is awesome but its stripping out some code that uses attribute selectors.

I use an icon set that is created from [Icomoon](https://icomoon.io). The css file they provide uses attribute selectors like [class^="icon-"], [class*=" icon-"] which is getting stripped out.

Is it just me or are these selectors not supported?

### PR DESCRIPTION
**Pull request by Illyism**
A step towards filtering on attribute selectors.

### CODE REVIEW

**Comment by kennyt** [comment]
This looks good so far. Will take a deeper look when I have time

**Comment by Illyism** [comment]
Thanks. It's unfinished according to the [spec](http://www.w3.org/TR/css3-selectors/#attribute-selectors). But at least it does not completely remove attribute selectors.

**Comment by karol-f** [comment]
+1

**Comment by kennyt** [comment]
Can you pull down the recent changes so the PR can be automatically merged?

Another thing with this is that if someone uses

```
.unused-link[href*="google"]
```

and the content doesn't use the class ```.unused-link``` it will still be in the output, correct? This is fine, as I'd rather have extra classes in the output than to be missing some classes (!). But this seems like it could be fixed

**Comment by Illyism** [comment]
@kennyt Done.

You're correct. Another solution is I'm sure possible but it seemed more necessary to fix it being removed completely.

Another issue is that if someone uses this:

```
a[href^="google"]
```

It would also match things like

```
"http://google.com"
```

While it should only match

```
"google.com"
```

**Comment by kennyt** [comment]
Thanks a lot

**Pull request merged**
