### PR TITLE
fix typo on cli

### PR DESCRIPTION
**Pull request by thewillhuang**

### CODE REVIEW

**Comment by kennyt** [comment]
That is the actual API for the CLI

**Comment by thewillhuang** [comment]
interesting, maybe something wrong with npm?

https://goo.gl/photos/rNzW2F7hoPPQ39Jb6

**Comment by Illyism** [comment]
@kennyt You need to bump the version after #44 and push changes to NPM.
NPM looks for the name in package.json, I added an alias in the linked commit in #44

**Comment by kennyt** [comment]
done

**Pull request closed without merging**
