### PR TITLE
--rejected option to log rejected rules

### PR DESCRIPTION
**Pull request by unwitting**
In response to #48, this adds a --rejected option which adds logging of the removed CSS rules.

### CODE REVIEW

**Comment by unwitting** [comment]
Sample output with --info and --rejected:

```
##################################
Before purify, CSS was 328456 chars long.
After purify, CSS is 315939 chars long. (1 times smaller)
##################################
This function took:  1402 ms
##################################
Rejected selectors:
blah
.blah
[yackety]
```

**Comment by corysimmons** [comment]
:+1: :+1: :+1:

**Comment by unwitting** [comment]
Added incentive for pull; I have another feature ready to PR that branches off this :)

**Comment by netproteus** [comment]
:+1: :+1: :+1:

**Comment by NikhilVerma** [comment]
:+1: We need this!

**Comment by unwitting** [comment]
@corysimmons feel free to use the fork if you need this in the meantime :)

**Comment by kennyt** [comment]
Cool, thanks for the PR. Give me a moment

**Comment by unwitting** [comment]
Anything need changing for the PR @kennyt?

**Comment by kennyt** [comment]
Looks good. Add it to the README and I'll merge it in.

**Comment by unwitting** [comment]
Done, thanks (๑˃̵ᴗ˂̵)و

**Comment by kennyt** [comment]
Thanks a lot.

**Comment by zerbons** [comment]
@kennyt can you publish a new version to npm with this feature?

**Pull request merged**
